# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: circleci/mongo:4.0.6
      - image: circleci/redis:5.0.2
      - image: circleci/mysql:8.0.3
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: 'test123456'
          MYSQL_DATABASE: mayday

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get install mysql-client
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 60s

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run test
          environment:
            CODECOV_TOKEN: 
          command: |
            . venv/bin/activate
            pytest --cov=./mayday/ tests/* -vv
            coverage xml --omit="./mayday/constants/*"
            python-codacy-coverage -r coverage.xml

      - store_artifacts:
          path: test-reports
          destination: test-reports

